version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - voting-network
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  server:
    build:
      context: ./servidor-votaciones
    ports:
      - "3000:3000"
    networks:
      - voting-network
    depends_on:
      - mongodb

networks:
  voting-network:
